### ISSUE TITLE
How to using RESTful API in ZKWeb?

### ISSUE THREAD

**Issue by Tuisku-L** [zkweb-framework/ZKWeb#1]
The ActionAttribute's path format is '/something',
But I want to use 'GET /something' and 'GET /something/{id}' to create RESTful API.
What should I do?
Thank you very muuuuuuuuch!

**Comment by 303248153** [comment]
For now there no direct support for url formatting like "/something/{id}",
because advance url matching have more overhead.
But I'm thinking to support it in zkweb 2.0, find a solution that won't cause performance impact.

**Comment by Tuisku-L** [comment]
Ok
I got it.Thanks!

**Comment by 303248153** [comment]
This feature is supported since 2.0 beta 9
