### ISSUE TITLE
IOC resolve abstract class throw exception

### ISSUE THREAD

**Issue by dynh** [zkweb-framework/ZKWeb#14]
```
	public abstract class ClassService {
		public abstract string GetName();
	}

        [ExportMany(ContractKey = "d")]
        public class TestResolveFromAbstract : ClassService
        {
            public override string GetName()
            {
                return "sunny";
            }
        }

        Assert.Equals(container.Resolve<ClassService>(IfUnresolved.Throw, "d").GetName(), "sunny");
```
The exception message:
`no factory registered to type ZKWebStandard.Tests.IocContainer.ContainerTest+ClassService and service key d`

**Comment by 303248153** [comment]
How did you register the service to container? the following methods are supported. 

-  `container.RegisterExports(typeof(TestResolveFromAbstract))`
- `container.RegisterMany<TestResolveFromAbstract>(serviceKey: "d")`
- `container.Register<ClassService, TestResolveFromAbstract>(serviceKey: "d")`

**Comment by 303248153** [comment]
Close since no feedback after months, if you have any issue please reopen it
