### ISSUE TITLE
Suggestion:ORM Add SmartSql

### ISSUE THREAD

**Issue by RocherKong** [zkweb-framework/ZKWeb#15]
能否加入对ORM:SmartSql支持
Can you add support for ORM: SmartSql?[SmartSql](https://github.com/dotnetcore/SmartSql)

**Comment by 303248153** [comment]
Looks like a great project, but I don't have much time to contribute 😮, anyway it's welcome to open a PR.

**Comment by RocherKong** [comment]
ok.I'll try while not busy.
