### ISSUE TITLE
Application.Ioc.AsServiceProvider() -> Not working AspNetCoreHostingModel : InProcess mode

### ISSUE THREAD

**Issue by ghost** [zkweb-framework/ZKWeb#16]
This is add 
<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>

App not run when Application.Ioc.AsServiceProvider(). 

Is there any way to fix it?

**Comment by 303248153** [comment]
Can you provide more details (like error messages), or better, a demo application?

**Comment by mz-core** [comment]
> Can you provide more details (like error messages), or better, a demo application?
H1
![H1](https://i.ibb.co/ZJrGbDc/Screenshot-9.png "Title")
H2
![H2](https://i.ibb.co/Ny5DTGd/Screenshot-10.png "Title")

If in Application.cs is not error. Can use only Container lib. Thanks ad

**Comment by 303248153** [comment]
Looks like you didn't use the [project creator](https://github.com/zkweb-framework/ZKWeb/tree/master/Tools), so it's hard to say where is the problem.
Can you upload this demo application?

**Comment by mz-core** [comment]
> Looks like you didn't use the [project creator](https://github.com/zkweb-framework/ZKWeb/tree/master/Tools), so it's hard to say where is the problem.
> Can you upload this demo application?

Dear ad,
I 've upload a litte demo with git [https://github.com/mz-core/zkweb-demo.git](url)
I didn't use the project creator. IoC for project 's simple used, i very like it. Thanks ad.

**Comment by 303248153** [comment]
I  run this demo application on ubuntu 16.04 by command `dotnet run` and it produces the expected result `["value1","value2","Demo Print"]` when access /api/values.
What is your environment, and what's the error message?

**Comment by 303248153** [comment]
Close since no reply in months, please reopen it if you have more informations.
